### ISSUE TITLE
Warning: Unexpected input(s) 'registry'

### ISSUE THREAD

**Issue by steadweb** [appleboy/docker-ecr-action#1]
Unable to deploy, registry isn't supported, error thrown in action:

```
Warning: Unexpected input(s) 'registry', valid inputs are ['entryPoint', 'args', 'access_key', 'secret_key', 'region', 'repo', 'lifecycle_policy', 'repository_policy', 'tags', 'dockerfile', 'auth', 'context', 'force_tag', 'insecure', 'mirror', 'bip', 'custom_dns', 'storage_driver', 'cache_from', 'auto_tag', 'daemon_off']
```

**Comment by appleboy** [comment]
Post your config and docker-ecr version?

**Comment by BadgerOps** [comment]
Hi @appleboy I'm seeing this as well, here is my github workflow:
```
      - name: Push to AWS ECR  # https://github.com/marketplace/actions/docker-ecr
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.aws_access_key_id }}
          secret_key: ${{ secrets.aws_secret_access_key }}
          registry: ${{ secrets.registry }}
          #cache_from: ${{ secrets.cache }}
          repo: image-name
          region: us-west-2
          tags: "latest"
          #auto_tag: true
          daemon_off: false
          dockerfile: ./web/Dockerfile
          context: ./web
```
`registry` variable is the full ECR registry path. 
This is nested under another build job as a separate step.
