### ISSUE TITLE
Multiple Tags Not Working

### ISSUE THREAD

**Issue by drnachio** [appleboy/docker-ecr-action#2]
I'm using this workflow:

```yaml
name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Build Docker image and push it to the registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.ACCESS_KEY_ID }}
          secret_key: ${{ secrets.SECRET_ACCESS_KEY }}
          cache_from: ${{ secrets.CACHE }}
          repo: mongo-backups
          region: eu-west-1
          tags: 'latest,${{ env.RELEASE_VERSION }}'
          dockerfile: Dockerfile
```

I verified that the tags value is: "latest,1.13.0"

But it adds no tag but `latest`:

![image](https://user-images.githubusercontent.com/5763165/97629465-6fb6c980-1a2e-11eb-903d-bdb0e68db588.png)
