### ISSUE TITLE
Warning: Unexpected input(s) 'build_args'

### ISSUE THREAD

**Issue by guilhermeblanco** [appleboy/docker-ecr-action#5]
When performing the following operation from a Rails app:

```
      - name: Build and push image to ECR
        id: build_push_docker_image
        uses: appleboy/docker-ecr-action@master
        env:
          REPOSITORY_REGISTRY: XXXX
          REPOSITORY_NAME: application
          MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: YYYY
          cache_from: ${{ env.REPOSITORY_REGISTRY }}/${{ env.REPOSITORY_NAME }}
          registry: ${{ env.REPOSITORY_REGISTRY }}
          repo: ${{ env.REPOSITORY_NAME }}
          dockerfile: Dockerfile
          tags: stage-${{ github.sha }}
          force_tag: true
          build_args: |
            "--secret id=master_key,env=MASTER_KEY"
```
